name: Deploy Next.js Project

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Prepare deployment
        run: |
          mkdir output
          cp -R out/* output/  

      - name: Commit and push to deploy branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B deploy  # Create or switch to the deploy branch
          rm -rf *  # Clear existing files in the deploy branch
          cp -R output/* .  # Copy output files to the root
          git add .
          git commit -m "Deploy Next.js build" || echo "Nothing to commit"
          git push origin deploy --force  # Push to the deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
